### PR TITLE
Interface methods

### PR DESCRIPTION
**Pull request by ericelliott**

### CODE REVIEW

**Comment by ericelliott** [comment]
The instance is a separate interface, and should be documented separately.

**Comment by Mouvedia** [comment]
Why would you separate `thing.prototype.method` from `thing`?

**Comment by ericelliott** [comment]
That's not what static means.

``` js
const delegatePrototype = {
  prototypeMethod () { return `I'm a prototype method`; }
}

const factory = () => {
  const privateProp = `I'm in the factory closure. Only factory methods can see me.`;

  return Object.assign(Object.create(delegatePrototype), {
    instanceMethod () { return `I'm an instance method.`; },
    getter () { return privateProp; }
  });
}

Object.assign(factory, {
  staticMethod () { return `I'm a static method: A method of the factory or constructor function.`; }
});

const instance = factory();

const output = `
  ${ instance.prototypeMethod() }
  ${ instance.instanceMethod() }
  ${ instance.getter() }
  ${ factory.staticMethod() }
`;

console.log(output);
```

**Comment by Mouvedia** [comment]
I never said it was static. It's an instance method.

Making the distinction between constructor method and prototype method is useless in our case. Showing the difference will have only one use case afaik: performance audit.

**Comment by ericelliott** [comment]
> Showing the difference will have only one use case afaik: performance audit.

That can be done without rtype. I think it's out of scope here.

**Comment by Mouvedia** [comment]
Ill open a new issue. It's off topic here.

**Pull request merged**
