### PR TITLE
confusion about the comma

### PR DESCRIPTION
**Pull request by Mouvedia**
several dependencies case

### CODE REVIEW

**Comment by ericelliott** [comment]
This is a confusing change. I would expect the `=>` to come immediately after the parameter list.

**Comment by jokeyrhyme** [comment]
If `=>`, `throws` and `requires` are keywords, then a tokeniser doesn't necessarily rely on commas to delimit these different clauses.

However, what can be parsed and what humans like to read are two different concerns. Maybe there is an idiomatic rtype style that can be linted, versus the locked down syntax that is enforced?
Or maybe we just have the locked down syntax with fixed orders and comma absence/presence? /shrug

**Comment by Mouvedia** [comment]
Maybe it's not the right place to do an example about the fact that there's not an established order.
So you can reject it if you want to showcase that elsewhere.

This PR is about whether the comma is required or not. Do you have an answer and a reason to back it up?

**Comment by jokeyrhyme** [comment]
If the function signature is supposed to look just like an ES2015 arrow function (with extra annotations), then I agree that having the `=>` clause immediately after the parameters parenthesis makes the most sense: e.g. `() => Type`.

**Comment by ericelliott** [comment]
I'm OK with optional commas if they're not needed to tokenize correctly. =)

**Pull request closed without merging**
