### PR TITLE
Adds rtype aim to README.

### LINKED ISSUE #106: Declaring rtype's aim(s)
It's a good idea to declare rtype's evolution directions. Currenly all we have is:

> - Great for simple documentation.
> - Compiler-agnostic type notation - for use with ECMAScript standard tools.
> - Can embed in JS as strings, for example with rfx. Affords easy runtime reflection.
> - Standing on the shoulders of giants. Inspired by: ES6, TypeScript, Haskell, Flow, & React

It lacks something like:
1. Aim to provide low learning curve for JS devs. **Or,**
2. Aim to provide better syntax than any other language.

@ericelliott could you please voice your suggestion here?

I personally would vote for **1**.

### PR DESCRIPTION
**Pull request by koresar**
Please, review the spelling and grammar. :)
Closes #106

### CODE REVIEW

**Comment by Mouvedia** [comment]
@koresar By "Should be a statement: no place for uncertainty." I meant that we don't "aim": we consider that it's a fact. The way you interpreted it is funny though :)
That is why I shortened it to an affirmation not a goal.

**Comment by koresar** [comment]
☺️
How about "No place for uncertainty for JS developers."?

**Comment by Mouvedia** [comment]
- Low learning curve thanks to the usage of a syntax specifically geared towards JS developers

It's turning into bikeshedding at this point though. @ericelliott hammer this please.

**Comment by koresar** [comment]
I'm totally fine with

> Low learning curve thanks to the usage of a syntax specifically geared towards JS developers

**Comment by Mouvedia** [comment]
It was directed to myself: I could discuss that sentence for hours :)

Settle for something simple like "low learning curve for EcmaScript developers" or wait for Eric's merge.

**Comment by ericelliott** [comment]
How about "Low learning curve for JavaScript developers"?

**Comment by Mouvedia** [comment]
https://davidmarkfans.wordpress.com/2010/08/13/comp-lang-javascript-javascript-vs-javascript/

**Pull request merged**
