### PR TITLE
returns keyword

### PR DESCRIPTION
**Pull request by Mouvedia**

### CODE REVIEW

**Comment by ericelliott** [comment]
One of these things does not belong. Big downvote. :-1:

**Comment by Mouvedia** [comment]
It seems like a very natural addition to me.
It's in line with the other `verb` + `s` keywords.

**Comment by ericelliott** [comment]
But it implies a type grouping that does not and should not exist. Different syntax rules apply for `=>` and [`throws:`, `requires:`].

**Comment by Mouvedia** [comment]
We could just apply the rules of `throws:` and `requires:` to `returns:` and be done with it.
`=>` would still have to always be placed just after `()`.

**Comment by ericelliott** [comment]
We could, but that would be a less accurate representation of the guiding design principle of rtype: intuitive for people who already know JavaScript. Even allowing `returns:` instead of `=>` breaks from the convention of JavaScript arrow functions, so that in itself would be a violation.

I follow your logic, I just disagree that it's the right direction for the spec.

**Comment by koresar** [comment]
I'd agree this Eric on that.

**Comment by Mouvedia** [comment]
I was waiting for another opinion to either continue or end the discussion.

**Comment by Mouvedia** [comment]
@ericelliott actually you were right: it would conflict with named types.

```
(paramName: Type)
  returns: name: Type,
  throws: Error
```

Now what happens if the name chosen was `returns`?

**Pull request closed without merging**
