### PR TITLE
An `interfaces.rtype` file

### PR DESCRIPTION
**Pull request by tomek-he-him**
As @Raynos [once mentioned](https://github.com/ericelliott/rtype/issues/47#issuecomment-162269856), it’d be useful to have a central per-project file to keep common interfaces. That’s where this custom interfaces thing really starts to make sense.

### CODE REVIEW

**Comment by ericelliott** [comment]
Nice. That begs the question, how do you get those definitions into `rfx`, but I suppose that's a question for `rfx` to answer. =)

**Comment by tomek-he-him** [comment]
`fs.readFileSync` is the easy way. :smiley:

**Comment by ericelliott** [comment]
Hmm.. we could compile the file to a `.js` module with predicates and function wrappers with a build step! Then, anywhere the user wants to take advantage of the types for rfx, they simply import the compiled output type checker objects...

**Comment by tomek-he-him** [comment]
That’s of course a much better idea! But since `fs.readFileSync` works even for the current scenario (rfx takes a `signature: String`), I wouldn’t put that on the MVP roadmap.

**Comment by ericelliott** [comment]
IMO, the compiler belongs in this repo, and the build step is a matter of compiler documentation, which would make sense in a "Getting Started" document here. `fs.readFileSync` is an obvious choice for a file loader that feeds into the compiler.

Then `rfx` projects simply `import`/`require` the built output as they would any other module.

**Comment by tomek-he-him** [comment]
Ah, alright! Makes sense!

**Comment by ericelliott** [comment]
:+1:

**Pull request merged**
