### PR TITLE
[#7] Use `|` for union types, like TypeScript

### PR DESCRIPTION
**Pull request by ericelliott**
See discussion: #7

### CODE REVIEW

**Comment by koresar** [comment]
Github is a smartass! 

> Pull requests that have a failing status can’t be merged from a phone.

Oh well. ☺

**Comment by ericelliott** [comment]
Why was it failing?

**Comment by troutowicz** [comment]
circleci problem I think.

```
npm test


> rtype@1.0.0 test /home/ubuntu/rtype
> babel-node test/index.js

sh: 1: babel-node: not found
npm ERR! Test failed.  See above for more details.

npm test returned exit code 1
```

**Comment by koresar** [comment]
I don't see babel here https://github.com/ericelliott/rtype/blob/master/package.json

**Comment by ericelliott** [comment]
Oops. This looks like my fault. I had it installed globally, so I never saw the failure on my machine.

**Comment by koresar** [comment]
Also, there is in no `test/index.js` in the repo :)

**Comment by ericelliott** [comment]
wat!?

**Comment by ericelliott** [comment]
looks like I forgot to commit the code. );

**Comment by koresar** [comment]
Push straight to the master. I believe it's okay for this repo. Don't bother PRs.

**Pull request merged**
