### PR TITLE
builtins

### PR DESCRIPTION
**Pull request by jokeyrhyme**
- as discussed previously:
  - https://github.com/ericelliott/rfx/pull/17
  - https://github.com/ericelliott/rfx/issues/16
- also added `isPredicate()` builtin predicate
  - although it executes it's argument to check the return type (is this okay?)
- not clear about the actual functionality for the exported `rtype()` function
  - signature: `rtype(type: Predicate | String) => Predicate`
  - if given a String, should it return an available matching builtin predicate? what if none match?
  - if given a Predicate, does it just return the Predicate?

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Oh, it's probably worth looking at the commits separately, otherwise this might be quite a large PR to take in all at once. /shrug

**Comment by ericelliott** [comment]
Looking good so far.

For now, if passed a predicate, `rtype()` should return the same predicate.

If passed a string, return a predicate that logs a warning message, something like "Warning: rtype string parsing is not implemented yet." and then return `true`.

In a separate PR we can probably do a first pass on a parser to find rtype builtin literals and return the corresponding predicates for them.

**Comment by jokeyrhyme** [comment]
Okay, I've implemented `rtype()` as you've suggested. Let me know if you need anything else. :)

**Comment by Mouvedia** [comment]
You should use `console.warn` if it's a warning and fallback on log if it's not supported.

**Comment by ericelliott** [comment]
> You should use console.warn if it's a warning and fallback on log if it's not supported.

:+1: 

No need to fall back on anything. It's supported in all major browsers + Node.

**Comment by ericelliott** [comment]
Cool.. time for part 2... the beginning of the parser. We should implement a tokenizer and build an AST. Have you done that before? You up for it?

**Comment by jokeyrhyme** [comment]
If inspiration strikes and nobody else has a PR open, I'll give it a whirl. I've walked ASTs before, but I've never made one myself. :)

**Comment by ericelliott** [comment]
Learning opportunities everywhere. =)

**Pull request merged**
