### PR TITLE
[Fixes #33] Predicate literals

### LINKED ISSUE #33: Predicate function as interface
If I understand the spec correctly, I can’t specify types like `Integer` through `interface` directly in the signature string. What do you guys think about this then:

``` js
type Integer (number) => (
  number === parseInt(number, 10)
)
```

### PR DESCRIPTION
**Pull request by ericelliott**
Also cleaned up order a bit for clarity.

### CODE REVIEW

**Comment by ericelliott** [comment]
See #33

**Comment by tomek-he-him** [comment]
I suggested another keyword `type` in https://github.com/ericelliott/rtype/issues/33#issue-118834814 because I thought you can create a function `interface`:

``` js
// interface NumberTransformer (Number) => Number

// addOne: NumberTransformer
export const addOne = (number) => number + 1;

// double: NumberTransformer
export const double = (number) => number * 2;
```

**Comment by ericelliott** [comment]
> I suggested another keyword type in #33 (comment) because I thought you can create a function interface...

Nope. This is not a valid function interface:

``` js
interface NumberTransformer (Number) => Number
```

It should be written like this:

``` js
NumberTransformer(Number) => Number // interface is implied for bare signatures
```

or like this:

``` js
interface NumberTransformer {
  (Number) => Number
}
```

**Comment by tomek-he-him** [comment]
Personally I don’t like 

``` js
NumberTransformer(Number) => Number // interface is implied for bare signatures
```

– how’s that different to

``` js
// NumberTransformer(Number) => Number
export const NumberTransformer = (a) => a;
```

?

**Comment by tomek-he-him** [comment]
But definitely :+1: to

``` js
interface NumberTransformer {
  (Number) => Number
}
```

My argument for `type` vs. `interface` is no longer relevant then.

**Comment by ericelliott** [comment]
> – how’s that different to

It's different because the idiomatic way to use signatures inline is to use a tool like rfx. The trouble with commented signatures is that they're not live code, and they're likely to fall out of sync (which is a problem with lots of JSDoc annotations).

**Comment by tomek-he-him** [comment]
Ahh, OK – I think I misunderstood your original comment. Sorry!

**Comment by tomek-he-him** [comment]
(I didn’t mean using comments for annotating function signatures. That was just a thought-shortcut.)

**Pull request merged**
