### PR TITLE
[#12] throws indicator

### PR DESCRIPTION
**Pull request by ericelliott**
See #12

### CODE REVIEW

**Comment by tomek-he-him** [comment]
:+1: So good to have this explicit!

> ``` js
> functionName() => String, throws // Is the same as:
> functionName() => String, throws Error
> ```
> 
> And throwing a generic `Error` type is a totally legit use-case.
> 
> — https://github.com/ericelliott/rtype/issues/12#issuecomment-158486865

How about making it stand out that `throws` is the equivalent of `throws Error`? Otherwise people can throw things like `{errorCode: 300, description: '...'}` and just say that their function `throws`.

**Comment by Mouvedia** [comment]
:-1:  I am against having a default Error type. I like the fact that you can say it throws without being too specific about it. It covers several types as well.
I know that we should advocate the throw Error but ppl will continue to throw stuff they shouldn't throw and that will require documentation as well.

**Comment by ericelliott** [comment]
@Mouvedia thrown errors are not going to be type checked. They're just going to throw.

`Error` is a generic case that will be satisfied by a specific error type like `TypeError`, just like a date string would still satisfy a `String` type check, or a `User` would still satisfy an `Object` type check.

It's the other way around that doesn't work. For instance, if you ask for a `TypeError`, and instead get a less specific `Error`, that would be a type constraint violation.

If people are returning random strings instead of proper error objects, they **should definitely get a type error**, because random strings don't have enough information to help developers debug the problem.

**Comment by Mouvedia** [comment]
I can agree in not being able to use `throws` for `throw 'don't do this'`.
But you should be able to do `throws String` in that case. rtype shouldn't be limited to good code.

**I want to be able to document bad code as well**.

**Comment by ericelliott** [comment]
> But you should be able to do throws String in that case... **I want to be able to document bad code as well.**

You can. `throws String` is a valid rtype denotation. I personally would chose `throws Error` and change the code from `throw 'some string';` to `throw new Error('some string');`.

If you're mucking around in the code anyway, might as well clean it up a little while you're there. ;)

**Pull request merged**
